# -*- coding: utf-8 -*-
"""BMI Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12M_sA5H3xo-eyDf8ePWVcKTVrNpCG0Ri
"""

# BMI = (weight in pounds * 703)/(height in inches ** 2)

name = input('Input your name: ')
weight = float(input('Enter your weight in pounds: '))
height = float(input('Enter your height in inches: '))
BMI = (weight * 703)/(height ** 2)

print(BMI)

if BMI>0:
    if(BMI < 18.5):
        print(name + ' you are underweight')
    elif(BMI <= 24.9):
        print(name + ' you are normal weight')
    elif(BMI <= 29.9):
        print(name + ' you are overweight')
    elif(BMI <= 34.9):
        print(name + ' you are obese')
    elif(BMI <= 39.9):
        print(name + ' you are severly obese')
    else:
        print(name + ' you are morbidly obese')
else:
    print('Enter valid input')